export enum CategorieNotification {
  FACTURE_CREEE = 'FACTURE_CREEE',
  RAPPEL_PAIEMENT = 'RAPPEL_PAIEMENT',
  FACTURE_RETARD = 'FACTURE_RETARD',
  PAIEMENT_RECU = 'PAIEMENT_RECU',
  FACTURE_SOLDEE = 'FACTURE_SOLDEE',
  FACTURE_ANNULEE = 'FACTURE_ANNULEE',
  RELANCE_AVANT_ECHEANCE = 'RELANCE_AVANT_ECHEANCE'
}