export enum TypeAlerte {
  STOCK_FAIBLE = 'STOCK_FAIBLE',
  STOCK_CRITIQUE = 'STOCK_CRITIQUE',
  RUPTURE_STOCK = 'RUPTURE_STOCK',
  STOCK_EXCESSIF = 'STOCK_EXCESSIF',
  PEREMPTION_PROCHE = 'PEREMPTION_PROCHE'
}